// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC547CDYIG5mMYxfrahRQGs8UGINNEKBQs',
    appId: '1:747855898697:web:82dbc2d0747f1aebe6f798',
    messagingSenderId: '747855898697',
    projectId: 'deliverappgfl-client',
    authDomain: 'deliverappgfl-client.firebaseapp.com',
    storageBucket: 'deliverappgfl-client.appspot.com',
    measurementId: 'G-THPJV7Q92W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApILvvAfSdgi3HaNR9OAl2ZEVWuHB97y0',
    appId: '1:747855898697:android:95f8c6ab386bc7cbe6f798',
    messagingSenderId: '747855898697',
    projectId: 'deliverappgfl-client',
    storageBucket: 'deliverappgfl-client.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4pCoH-KPt2iKKe7t70drjBthcbz8VRbM',
    appId: '1:747855898697:ios:a5373d69634acc1be6f798',
    messagingSenderId: '747855898697',
    projectId: 'deliverappgfl-client',
    storageBucket: 'deliverappgfl-client.appspot.com',
    androidClientId: '747855898697-9cn3kts9v518s7s3jt67b7nk3f16qa5q.apps.googleusercontent.com',
    iosClientId: '747855898697-7dt2n00p7a4ehdl7a59bm1736podon6b.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliverClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4pCoH-KPt2iKKe7t70drjBthcbz8VRbM',
    appId: '1:747855898697:ios:145af529e5dcb053e6f798',
    messagingSenderId: '747855898697',
    projectId: 'deliverappgfl-client',
    storageBucket: 'deliverappgfl-client.appspot.com',
    androidClientId: '747855898697-9cn3kts9v518s7s3jt67b7nk3f16qa5q.apps.googleusercontent.com',
    iosClientId: '747855898697-2lc84ocqbtugrdj6k9h1d4mopur9cjrp.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliverClient.RunnerTests',
  );
}
